INSERT INTO $diot_infterdetiva$
SELECT
    identidecla.rfcdeclarante,
    contribuyente.bo_id,
    identidecla.numerooperacion,
    identidecla.fechapresentacion,
    contribuyente.razonsocial,
    declaracion.peridiocidad,
    declaracion.periodo,
    declaracion.tipodeclara,
    declaracion.tipocomp,
    explodedTerDecla.numeroconsecutivoperacion,
    explodedTerDecla.tipotercero,
    explodedTerDecla.tipoperacion,
    explodedTerDecla.rfctercerodeclarado,
    explodedTerDecla.numeroidfiscal,
    explodedTerDecla.nombreextranjero,
    explodedTerDecla.paisjurisdiccionresidenciafiscal,
    explodedTerDecla.especificalugarjurisdiccionfiscal,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactipagtasa16iva AS DECIMAL(16,0)) AS valactactipagtasa16iva,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.ivapagatasa16 AS DECIMAL(16,0)) AS ivapagatasa16,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.montoivapagadonoacreditasa16 AS DECIMAL(16,0)) AS montoivapagadonoacreditasa16,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactipagatasa11iva AS DECIMAL(16,0)) AS valactactipagatasa11iva,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.ivapagadotasa11 AS DECIMAL(16,0)) AS ivapagadotasa11,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.montoivapagadonoacreditasa11 AS DECIMAL(16,0)) AS montoivapagadonoacreditasa11,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactipagarfn AS DECIMAL(16,0)) AS valactactipagarfn,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.ivapagarfn AS DECIMAL(16,0)) AS ivapagarfn,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.montoivapagadonoacredirfn AS DECIMAL(16,0)) AS montoivapagadonoacredirfn,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactipagarfs AS DECIMAL(16,0)) AS valactactipagarfs,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.ivapagadorfs AS DECIMAL(16,0)) AS ivapagadorfs,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.montoivapagadonoacredirfs AS DECIMAL(16,0)) AS montoivapagadonoacredirfs,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactipagaimpbienservitasa16iva AS DECIMAL(16,0)) AS valactactipagaimpbienservitasa16iva,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.ivapagaimpbienservitasa16iva AS DECIMAL(16,0)) AS ivapagaimpbienservitasa16iva,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.montoivapaganoacreimporbienservtasa16iva AS DECIMAL(16,0)) AS montoivapaganoacreimporbienservtasa16iva,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactipagaimpobienservinopagaivaexento AS DECIMAL(16,0)) AS valactactipagaimpobienservinopagaivaexento,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactipaganopagaivaexe AS DECIMAL(16,0)) AS valactactipaganopagaivaexe,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactipagatasa0iva AS DECIMAL(16,0)) AS valactactipagatasa0iva,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.valactactinoobjiva AS DECIMAL(16,0)) AS valactactinoobjiva,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.ivapagaretenido AS DECIMAL(16,0)) AS ivapagaretenido,
    CAST(explodedTerDecla.IvaDeclararPorTerceroProveedor.ivapagadevdesbonsobadqmercgastgener AS DECIMAL(16,0)) AS ivapagadevdesbonsobadqmercgastgener,
    CAST(explodedTerDecla.ValorActActi.valtotactactipagarfn AS DECIMAL(16,0)) AS valtotactactipagarfn,
    CAST(explodedTerDecla.ValorActActi.devdesbonrfn AS DECIMAL(16,0)) AS devdesbonrfn,
    CAST(explodedTerDecla.ValorActActi.valnetactactipagarfn AS DECIMAL(16,0)) AS valnetactactipagarfn,
    CAST(explodedTerDecla.ValorActActi.ivapagadorfndet AS DECIMAL(16,0)) AS ivapagadorfndet,
    CAST(explodedTerDecla.ValorActActi.valtotactactipagarfs AS DECIMAL(16,0)) AS valtotactactipagarfs,
    CAST(explodedTerDecla.ValorActActi.devdesbonrfs AS DECIMAL(16,0)) AS devdesbonrfs,
    CAST(explodedTerDecla.ValorActActi.valnetactactipagarfs AS DECIMAL(16,0)) AS valnetactactipagarfs,
    CAST(explodedTerDecla.ValorActActi.ivapagadorfsdet AS DECIMAL(16,0)) AS ivapagadorfsdet,
    CAST(explodedTerDecla.ValorActActi.valtotactactipagarf AS DECIMAL(16,0)) AS valtotactactipagarf,
    CAST(explodedTerDecla.ValorActActi.devdesbonrf AS DECIMAL(16,0)) AS devdesbonrf,
    CAST(explodedTerDecla.ValorActActi.valnetactactipagarf AS DECIMAL(16,0)) AS valnetactactipagarf,
    CAST(explodedTerDecla.ValorActActi.ivapagarf AS DECIMAL(16,0)) AS ivapagarf,
    CAST(explodedTerDecla.ValorActActi.valtotactactipagatasa16iva AS DECIMAL(16,0)) AS valtotactactipagatasa16iva,
    CAST(explodedTerDecla.ValorActActi.devdesbontasa16iva AS DECIMAL(16,0)) AS devdesbontasa16iva,
    CAST(explodedTerDecla.ValorActActi.valnetactactipagatasa16iva AS DECIMAL(16,0)) AS valnetactactipagatasa16iva,
    CAST(explodedTerDecla.ValorActActi.ivapagatasa16det AS DECIMAL(16,0)) AS ivapagatasa16det,
    CAST(explodedTerDecla.ValorActActi.ivapagaagresinincimpor AS DECIMAL(16,0)) AS ivapagaagresinincimpor,
    CAST(explodedTerDecla.ValorActActi.valtotactactipagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS valtotactactipagaimporaduabientangtasa16iva,
    CAST(explodedTerDecla.ValorActActi.devdesbonimporaduabientangtasa16iva AS DECIMAL(16,0)) AS devdesbonimporaduabientangtasa16iva,
    CAST(explodedTerDecla.ValorActActi.valnetactactiimporaduabientangtasa16iva AS DECIMAL(16,0)) AS valnetactactiimporaduabientangtasa16iva,
    CAST(explodedTerDecla.ValorActActi.ivapagaimporaduabientangtasa16 AS DECIMAL(16,0)) AS ivapagaimporaduabientangtasa16,
    CAST(explodedTerDecla.ValorActActi.valtotactactipagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS valtotactactipagaimporbienintangservtasa16iva,
    CAST(explodedTerDecla.ValorActActi.devdesbonimporbienintangservtasa16iva AS DECIMAL(16,0)) AS devdesbonimporbienintangservtasa16iva,
    CAST(explodedTerDecla.ValorActActi.valnetactactiimporbienintangservtasa16iva AS DECIMAL(16,0)) AS valnetactactiimporbienintangservtasa16iva,
    CAST(explodedTerDecla.ValorActActi.ivapagaimporbienintangservtasa16 AS DECIMAL(16,0)) AS ivapagaimporbienintangservtasa16,
    CAST(explodedTerDecla.ValorActActi.ivapagsumimpvalagreincluimpor AS DECIMAL(16,0)) AS ivapagsumimpvalagreincluimpor,
    CAST(explodedTerDecla.IvaAcreditable.excluactgravrfn AS DECIMAL(16,0)) AS excluactgravrfn,
    CAST(explodedTerDecla.IvaAcreditable.asoacticualaplproprfn AS DECIMAL(16,0)) AS asoacticualaplproprfn,
    CAST(explodedTerDecla.IvaAcreditable.ivaacrerfn AS DECIMAL(16,0)) AS ivaacrerfn,
    CAST(explodedTerDecla.IvaAcreditable.excluactgravrfs AS DECIMAL(16,0)) AS excluactgravrfs,
    CAST(explodedTerDecla.IvaAcreditable.asoactcualaplproprfs AS DECIMAL(16,0)) AS asoactcualaplproprfs,
    CAST(explodedTerDecla.IvaAcreditable.ivaacrerfs AS DECIMAL(16,0)) AS ivaacrerfs,
    CAST(explodedTerDecla.IvaAcreditable.excluactgravrf AS DECIMAL(16,0)) AS excluactgravrf,
    CAST(explodedTerDecla.IvaAcreditable.asoactcualaplproprf AS DECIMAL(16,0)) AS asoactcualaplproprf,
    CAST(explodedTerDecla.IvaAcreditable.ivaacrerf AS DECIMAL(16,0)) AS ivaacrerf,
    CAST(explodedTerDecla.IvaAcreditable.excluactgravpagatasa16iva AS DECIMAL(16,0)) AS excluactgravpagatasa16iva,
    CAST(explodedTerDecla.IvaAcreditable.asoacticualapliproppagatasa16iva AS DECIMAL(16,0)) AS asoacticualapliproppagatasa16iva,
    CAST(explodedTerDecla.IvaAcreditable.ivaacrepagatasa16 AS DECIMAL(16,0)) AS ivaacrepagatasa16,
    CAST(explodedTerDecla.IvaAcreditable.excluactigravsininclimpor AS DECIMAL(16,0)) AS excluactigravsininclimpor,
    CAST(explodedTerDecla.IvaAcreditable.asoacticualaplipropsininclimpor AS DECIMAL(16,0)) AS asoacticualaplipropsininclimpor,
    CAST(explodedTerDecla.IvaAcreditable.ivaacresininclimpor AS DECIMAL(16,0)) AS ivaacresininclimpor,
    CAST(explodedTerDecla.IvaAcreditable.excluactigravpagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS excluactigravpagaimporaduabientangtasa16iva,
    CAST(explodedTerDecla.IvaAcreditable.asoacticualapliproppagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS asoacticualapliproppagaimporaduabientangtasa16iva,
    CAST(explodedTerDecla.IvaAcreditable.ivaacrepagaimpoaduabientangtasa16iva AS DECIMAL(16,0)) AS ivaacrepagaimpoaduabientangtasa16iva,
    CAST(explodedTerDecla.IvaAcreditable.excluactigravpagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS excluactigravpagaimporbienintangservtasa16iva,
    CAST(explodedTerDecla.IvaAcreditable.asoactiapliproppagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS asoactiapliproppagaimporbienintangservtasa16iva,
    CAST(explodedTerDecla.IvaAcreditable.ivaacrepagaimporbienintangservtasa16 AS DECIMAL(16,0)) AS ivaacrepagaimporbienintangservtasa16,
    CAST(explodedTerDecla.IvaAcreditable.excluactigravsumaivaincluimpor AS DECIMAL(16,0)) AS excluactigravsumaivaincluimpor,
    CAST(explodedTerDecla.IvaAcreditable.asoacticuaaplpropsumaivaincluimpor AS DECIMAL(16,0)) AS asoacticuaaplpropsumaivaincluimpor,
    CAST(explodedTerDecla.IvaAcreditable.ivaacresumaivaincluimpor AS DECIMAL(16,0)) AS ivaacresumaivaincluimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.asoacticualaplproprfndet AS DECIMAL(16,0)) AS asoacticualaplproprfndet,
    CAST(explodedTerDecla.IvaNoAcreditable.asonocumpreqrfn AS DECIMAL(16,0)) AS asonocumpreqrfn,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiexerfn AS DECIMAL(16,0)) AS asoactiexerfn,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactinoobjrfn AS DECIMAL(16,0)) AS asoactinoobjrfn,
    CAST(explodedTerDecla.IvaNoAcreditable.totpagarfn AS DECIMAL(16,0)) AS totpagarfn,
    CAST(explodedTerDecla.IvaNoAcreditable.asoacticualaplproprfsdet AS DECIMAL(16,0)) AS asoacticualaplproprfsdet,
    CAST(explodedTerDecla.IvaNoAcreditable.asonocumpreqrfs AS DECIMAL(16,0)) AS asonocumpreqrfs,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiexerfs AS DECIMAL(16,0)) AS asoactiexerfs,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactinoobjrfs AS DECIMAL(16,0)) AS asoactinoobjrfs,
    CAST(explodedTerDecla.IvaNoAcreditable.totpagarfs AS DECIMAL(16,0)) AS totpagarfs,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactcualaplproprfdet AS DECIMAL(16,0)) AS asoactcualaplproprfdet,
    CAST(explodedTerDecla.IvaNoAcreditable.asonocumpreqrf AS DECIMAL(16,0)) AS asonocumpreqrf,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiexerf AS DECIMAL(16,0)) AS asoactiexerf,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactinoobjrf AS DECIMAL(16,0)) AS asoactinoobjrf,
    CAST(explodedTerDecla.IvaNoAcreditable.totpagarf AS DECIMAL(16,0)) AS totpagarf,
    CAST(explodedTerDecla.IvaNoAcreditable.asoacticualapliproptasa16iva AS DECIMAL(16,0)) AS asoacticualapliproptasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asonocumpreqtasa16iva AS DECIMAL(16,0)) AS asonocumpreqtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiexetasa16iva AS DECIMAL(16,0)) AS asoactiexetasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactinoobjtasa16iva AS DECIMAL(16,0)) AS asoactinoobjtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.tottasa16iva AS DECIMAL(16,0)) AS tottasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiaplipropivasininclimpor AS DECIMAL(16,0)) AS asoactiaplipropivasininclimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.asonocumpreqivasinincimpor AS DECIMAL(16,0)) AS asonocumpreqivasinincimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiexeivasininclimpor AS DECIMAL(16,0)) AS asoactiexeivasininclimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactinoobjivasininclimpor AS DECIMAL(16,0)) AS asoactinoobjivasininclimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.totivasininclimpor AS DECIMAL(16,0)) AS totivasininclimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.asoacticualaplipropimporaduabientangtasa16iva AS DECIMAL(16,0)) AS asoacticualaplipropimporaduabientangtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asonocumpreqimporaduabientangtasa16iva AS DECIMAL(16,0)) AS asonocumpreqimporaduabientangtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiexeimporaduabientangtasa16iva AS DECIMAL(16,0)) AS asoactiexeimporaduabientangtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactinoobjimporaduabientangtasa16iva AS DECIMAL(16,0)) AS asoactinoobjimporaduabientangtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.totimporaduabientangtasa16iva AS DECIMAL(16,0)) AS totimporaduabientangtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoacticualaplipropimporbienintangservtasa16iva AS DECIMAL(16,0)) AS asoacticualaplipropimporbienintangservtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asonocumpreqimporbienintangservtasa16iva AS DECIMAL(16,0)) AS asonocumpreqimporbienintangservtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiexeimporbienintangservtasa16iva AS DECIMAL(16,0)) AS asoactiexeimporbienintangservtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactinoobjimporbienintangservtasa16iva AS DECIMAL(16,0)) AS asoactinoobjimporbienintangservtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.totimporbienintangservtasa16iva AS DECIMAL(16,0)) AS totimporbienintangservtasa16iva,
    CAST(explodedTerDecla.IvaNoAcreditable.asoacticualaplipropincluimpor AS DECIMAL(16,0)) AS asoacticualaplipropincluimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.asonocumpreqincluimpor AS DECIMAL(16,0)) AS asonocumpreqincluimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactiexeincluimpor AS DECIMAL(16,0)) AS asoactiexeincluimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.asoactinoobjincluimpor AS DECIMAL(16,0)) AS asoactinoobjincluimpor,
    CAST(explodedTerDecla.IvaNoAcreditable.totincluimpor AS DECIMAL(16,0)) AS totincluimpor,
    CAST(explodedTerDecla.DatosAdicionales.ivaretenidocontribupaga AS DECIMAL(16,0)) AS ivaretenidocontribupaga,
    CAST(explodedTerDecla.DatosAdicionales.valactactipagaimporbienservnopagaivaexe AS DECIMAL(16,0)) AS valactactipagaimporbienservnopagaivaexe,
    CAST(explodedTerDecla.DatosAdicionales.valactactipaganopagaivaexedet AS DECIMAL(16,0)) AS valactactipaganopagaivaexedet,
    CAST(explodedTerDecla.DatosAdicionales.valdemaactactipagatasa0iva AS DECIMAL(16,0)) AS valdemaactactipagatasa0iva,
    CAST(explodedTerDecla.DatosAdicionales.valactactinoobjivarealterrnac AS DECIMAL(16,0)) AS valactactinoobjivarealterrnac,
    CAST(explodedTerDecla.DatosAdicionales.valactactinoobjivanocontestabterrnac AS DECIMAL(16,0)) AS valactactinoobjivanocontestabterrnac,
    CAST(explodedTerDecla.DatosAdicionales.manidioefecfisccompampoperrealprovdet AS STRING) AS manidioefecfisccompampoperrealprovdet,
    id_ejecucion,
    fechadesdoble AS fechacargadwh,
    FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP, "America/Mexico_City") AS fechadesdoble,
    p_fechapresentacion,
    'I' AS operacion,
    explodedTerDecla.fila AS fila,
    NULL AS decreto,
    NULL AS valactactiemiaplicestim,
    NULL AS ivanocobapliestimfiscal,
    NULL AS valactactireciapliestimfiscal,
    NULL AS ivanopagapliestifiscal
FROM(
    SELECT *, explode(DatosDelTerceroDeclarado) AS explodedTerDecla
    FROM $plata_diot_infterdetiva$
    WHERE id_ejecucion = '$IDBATCH$' or numeroOperacion in ($NUMEROSOPERACION$)
    AND admindeclaracion IS NOT NULL $PARTITION_FILTER$
);