INSERT INTO $diot_infterdetiva$
SELECT
    identidecla.rfcdeclarante,
    contribuyente.bo_id,
    identidecla.numerooperacion,
    identidecla.fechapresentacion,
    contribuyente.razonsocial,
    declaracion.peridiocidad,
    declaracion.periodo,
    declaracion.tipodeclara,
    declaracion.tipocomp,
    NULL AS numeroconsecutivoperacion,
    NULL AS tipotercero,
    NULL AS tipoperacion,
    NULL AS rfctercerodeclarado,
    NULL AS numeroidfiscal,
    NULL AS nombreextranjero,
    NULL AS paisjurisdiccionresidenciafiscal,
    NULL AS especificalugarjurisdiccionfiscal,
    NULL AS valactactipagtasa16iva,
    NULL AS ivapagatasa16,
    NULL AS montoivapagadonoacreditasa16,
    NULL AS valactactipagatasa11iva,
    NULL AS ivapagadotasa11,
    NULL  AS montoivapagadonoacreditasa11,
    NULL AS valactactipagarfn,
    NULL AS ivapagarfn,
    NULL AS montoivapagadonoacredirfn,
    NULL AS valactactipagarfs,
    NULL AS ivapagadorfs,
    NULL AS montoivapagadonoacredirfs,
    NULL AS valactactipagaimpbienservitasa16iva,
    NULL AS ivapagaimpbienservitasa16iva,
    NULL AS montoivapaganoacreimporbienservtasa16iva,
    NULL AS valactactipagaimpobienservinopagaivaexento,
    NULL AS valactactipaganopagaivaexe,
    NULL AS valactactipagatasa0iva,
    NULL AS valactactinoobjiva,
    NULL AS ivapagaretenido,
    NULL AS ivapagadevdesbonsobadqmercgastgener,
    NULL AS valtotactactipagarfn,
    NULL AS devdesbonrfn,
    NULL AS valnetactactipagarfn,
    NULL AS ivapagadorfndet,
    NULL AS valtotactactipagarfs,
    NULL AS devdesbonrfs,
    NULL AS valnetactactipagarfs,
    NULL AS ivapagadorfsdet,
    NULL AS valtotactactipagarf,
    NULL AS devdesbonrf,
    NULL AS valnetactactipagarf,
    NULL AS ivapagarf,
    NULL AS valtotactactipagatasa16iva,
    NULL AS devdesbontasa16iva,
    NULL AS valnetactactipagatasa16iva,
    NULL AS ivapagatasa16det,
    NULL AS ivapagaagresinincimpor,
    NULL AS valtotactactipagaimporaduabientangtasa16iva,
    NULL AS devdesbonimporaduabientangtasa16iva,
    NULL AS valnetactactiimporaduabientangtasa16iva,
    NULL AS ivapagaimporaduabientangtasa16,
    NULL AS valtotactactipagaimporbienintangservtasa16iva,
    NULL AS devdesbonimporbienintangservtasa16iva,
    NULL AS valnetactactiimporbienintangservtasa16iva,
    NULL AS ivapagaimporbienintangservtasa16,
    NULL AS ivapagsumimpvalagreincluimpor,
    NULL AS excluactgravrfn,
    NULL AS asoacticualaplproprfn,
    NULL AS ivaacrerfn,
    NULL AS excluactgravrfs,
    NULL AS asoactcualaplproprfs,
    NULL AS ivaacrerfs,
    NULL AS excluactgravrf,
    NULL AS asoactcualaplproprf,
    NULL AS ivaacrerf,
    NULL AS excluactgravpagatasa16iva,
    NULL AS asoacticualapliproppagatasa16iva,
    NULL AS ivaacrepagatasa16,
    NULL AS excluactigravsininclimpor,
    NULL AS asoacticualaplipropsininclimpor,
    NULL AS ivaacresininclimpor,
    NULL AS excluactigravpagaimporaduabientangtasa16iva,
    NULL AS asoacticualapliproppagaimporaduabientangtasa16iva,
    NULL AS ivaacrepagaimpoaduabientangtasa16iva,
    NULL AS excluactigravpagaimporbienintangservtasa16iva,
    NULL AS asoactiapliproppagaimporbienintangservtasa16iva,
    NULL AS ivaacrepagaimporbienintangservtasa16,
    NULL AS excluactigravsumaivaincluimpor,
    NULL AS asoacticuaaplpropsumaivaincluimpor,
    NULL AS ivaacresumaivaincluimpor,
    NULL AS asoacticualaplproprfndet,
    NULL AS asonocumpreqrfn,
    NULL AS asoactiexerfn,
    NULL AS asoactinoobjrfn,
    NULL AS totpagarfn,
    NULL AS asoacticualaplproprfsdet,
    NULL AS asonocumpreqrfs,
    NULL AS asoactiexerfs,
    NULL AS asoactinoobjrfs,
    NULL AS totpagarfs,
    NULL AS asoactcualaplproprfdet,
    NULL AS asonocumpreqrf,
    NULL AS asoactiexerf,
    NULL AS asoactinoobjrf,
    NULL AS totpagarf,
    NULL AS asoacticualapliproptasa16iva,
    NULL AS asonocumpreqtasa16iva,
    NULL AS asoactiexetasa16iva,
    NULL AS asoactinoobjtasa16iva,
    NULL AS tottasa16iva,
    NULL AS asoactiaplipropivasininclimpor,
    NULL AS asonocumpreqivasinincimpor,
    NULL AS asoactiexeivasininclimpor,
    NULL AS asoactinoobjivasininclimpor,
    NULL AS totivasininclimpor,
    NULL AS asoacticualaplipropimporaduabientangtasa16iva,
    NULL AS asonocumpreqimporaduabientangtasa16iva,
    NULL AS asoactiexeimporaduabientangtasa16iva,
    NULL AS asoactinoobjimporaduabientangtasa16iva,
    NULL AS totimporaduabientangtasa16iva,
    NULL AS asoacticualaplipropimporbienintangservtasa16iva,
    NULL AS asonocumpreqimporbienintangservtasa16iva,
    NULL AS asoactiexeimporbienintangservtasa16iva,
    NULL AS asoactinoobjimporbienintangservtasa16iva,
    NULL AS totimporbienintangservtasa16iva,
    NULL AS asoacticualaplipropincluimpor,
    NULL AS asonocumpreqincluimpor,
    NULL AS asoactiexeincluimpor,
    NULL AS asoactinoobjincluimpor,
    NULL AS totincluimpor,
    NULL AS ivaretenidocontribupaga,
    NULL AS valactactipagaimporbienservnopagaivaexe,
    NULL AS valactactipaganopagaivaexedet,
    NULL AS valdemaactactipagatasa0iva,
    NULL AS valactactinoobjivarealterrnac,
    NULL AS valactactinoobjivanocontestabterrnac,
    NULL AS manidioefecfisccompampoperrealprovdet,
    id_ejecucion,
    fechadesdoble AS fechacargadwh,
    FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP, "America/Mexico_City") AS fechadesdoble,
    p_fechapresentacion,
    'I' AS operacion,
    explodedDatosInfor.fila AS fila,
    explodedDatosInfor.decreto AS decreto,
    CAST(explodedDatosInfor.valactactiemiaplicestim AS DECIMAL(16,0)) AS valactactiemiaplicestim,
    CAST(explodedDatosInfor.ivanocobapliestimfiscal AS DECIMAL(16,0)) AS ivanocobapliestimfiscal,
    CAST(explodedDatosInfor.valactactireciapliestimfiscal AS DECIMAL(16,0)) AS valactactireciapliestimfiscal,
    CAST(explodedDatosInfor.ivanopagapliestifiscal AS DECIMAL(16,0)) AS ivanopagapliestifiscal
FROM(
    SELECT *, explode(DetDatosInformativos) AS explodedDatosInfor
    FROM $plata_diot_infterdetiva$
    WHERE id_ejecucion = '$IDBATCH$' or numeroOperacion in ($NUMEROSOPERACION$)
    AND admindeclaracion IS NOT NULL $PARTITION_FILTER$
);