WITH infototreportados AS(
    SELECT
        rfc,
        contribuyente.bo_id,
        identidecla.numerooperacion,
        identidecla.fechapresentacion,
        id_ejecucion,
        contribuyente.razonsocial,
        declaracion.peridiocidad,
        declaracion.periodo,
        declaracion.tipodeclara,
        declaracion.tipocomp,
        Totales.InfoTotReportados.valtotactactipagatasa16ivatot,
        Totales.InfoTotReportados.ivapagatasa16tot,
        Totales.InfoTotReportados.montivapaganoacretasa16,
        Totales.InfoTotReportados.valtotactactipagatasa11,
        Totales.InfoTotReportados.ivapagatasa11tot,
        Totales.InfoTotReportados.montivapaganoacretasa11,
        Totales.InfoTotReportados.valactactipagarfntot,
        Totales.InfoTotReportados.ivapagarfntot,
        Totales.InfoTotReportados.montivapaganoacrerfn,
        Totales.InfoTotReportados.valactactirfs,
        Totales.InfoTotReportados.ivapagarfstot,
        Totales.InfoTotReportados.montivapaganoacrerfs,
        Totales.InfoTotReportados.ivapagatrslacontri,
        Totales.InfoTotReportados.montoivapaganoacretrslacontri,
        Totales.InfoTotReportados.valactactipagaimpbienservitasa16ivatot,
        Totales.InfoTotReportados.ivapagaimpbienservitasa16ivatot,
        Totales.InfoTotReportados.montivapaganoacreimporbienservtasa16,
        Totales.InfoTotReportados.valactactipagaimpobienservinopagaivaexentotot,
        Totales.InfoTotReportados.valactactipaganopagaivaexentotot,
        Totales.InfoTotReportados.demasactactipagatasa0iva,
        Totales.InfoTotReportados.actactinoobjiva,
        Totales.InfoTotReportados.ivapagretecontribu,
        Totales.InfoTotReportados.ivapagadevdesbonsobadqmercgastgenertot,
        fechadesdoble,
        p_fechapresentacion
    FROM(
         SELECT  *
         FROM    $plata_diot_inftotimpiva$
         WHERE   id_ejecucion = '$IDBATCH$' or numeroOperacion in ($NUMEROSOPERACION$)
         AND admindeclaracion IS NOT NULL $PARTITION_FILTER$
    )
),
valactactitotales AS(
    SELECT
        rfc,
        contribuyente.bo_id,
        identidecla.numerooperacion,
        identidecla.fechapresentacion,
        id_ejecucion,
        contribuyente.razonsocial,
        declaracion.peridiocidad,
        declaracion.periodo,
        declaracion.tipodeclara,
        declaracion.tipocomp,
        Totales.ValActActi.valactactipagarfntota,
        Totales.ValActActi.devdesbonactactipagarfn,
        Totales.ValActActi.valnetactactipagarfntot,
        Totales.ValActActi.ivapagaactactipagarfn,
        Totales.ValActActi.valactactipagarfstot,
        Totales.ValActActi.devdesbonactactipagarfs,
        Totales.ValActActi.valnetactactipagarfstot,
        Totales.ValActActi.ivapagaactactipagarfs,
        Totales.ValActActi.valactactipagarf,
        Totales.ValActActi.devdesbonactactipagarf,
        Totales.ValActActi.valnetactactipagarftot,
        Totales.ValActActi.ivapagaactactipagarf,
        Totales.ValActActi.valactactitotpagatasa16iva,
        Totales.ValActActi.devdesbontotpagatasa16iva,
        Totales.ValActActi.valnetactactipagatasa16ivatot,
        Totales.ValActActi.ivapagatotpagatasa16tot,
        Totales.ValActActi.ivapagasinincluimpor,
        Totales.ValActActi.valactactipagaimporaduabientangtasa16iva,
        Totales.ValActActi.devdesbonpagaimporaduabientangtasa16iva,
        Totales.ValActActi.valnetactactipagaimporaduabientangtasa16iva,
        Totales.ValActActi.ivapagaimporaduabientangtasa16tot,
        Totales.ValActActi.valactactipagaimporbienintangservtasa16iva,
        Totales.ValActActi.devdesbonpagaimporbienintangservtasa16iva,
        Totales.ValActActi.valnetactactipagaimporbienintangservtasa16iva,
        Totales.ValActActi.ivapagaimporbienintangservtasa16tot,
        Totales.ValActActi.ivapagasumimpvalagreincluimpor
    FROM(
        SELECT  *
        FROM    $plata_diot_inftotimpiva$
        WHERE   id_ejecucion = '$IDBATCH$' or numeroOperacion in ($NUMEROSOPERACION$)
        AND admindeclaracion IS NOT NULL $PARTITION_FILTER$
    )
),
ivaacreditabletot AS(
    SELECT
        rfc,
        contribuyente.bo_id,
        identidecla.numerooperacion,
        identidecla.fechapresentacion,
        id_ejecucion,
        contribuyente.razonsocial,
        declaracion.peridiocidad,
        declaracion.periodo,
        declaracion.tipodeclara,
        declaracion.tipocomp,
        Totales.IvaAcreditableTot.excluactigravpagarfn,
        Totales.IvaAcreditableTot.asoacticualapliproppagarfntot,
        Totales.IvaAcreditableTot.ivaacrepagarfn,
        Totales.IvaAcreditableTot.excluactigravpagarfs,
        Totales.IvaAcreditableTot.asoacticualapliproppagarfstot,
        Totales.IvaAcreditableTot.ivaacrepagarfs,
        Totales.IvaAcreditableTot.excluactigravpagarf,
        Totales.IvaAcreditableTot.asoacticualapliproppagarf,
        Totales.IvaAcreditableTot.ivaacrepagarf,
        Totales.IvaAcreditableTot.excluactigravtotpagatasa16iva,
        Totales.IvaAcreditableTot.asoacticualapliproppagatasa16ivatot,
        Totales.IvaAcreditableTot.ivaacretotpagatasa16,
        Totales.IvaAcreditableTot.excluactigravivaincluimpor,
        Totales.IvaAcreditableTot.asoactiaplipropivasininclimportot,
        Totales.IvaAcreditableTot.ivaacreivasininclimpor,
        Totales.IvaAcreditableTot.excluactigravpagaimporaduabientangtasa16ivatot,
        Totales.IvaAcreditableTot.asoacticualapliproppagaimporaduabientangtasa16ivatot,
        Totales.IvaAcreditableTot.ivaacrepagaimpoaduabientangtasa16ivatot,
        Totales.IvaAcreditableTot.excluactigravpagaimporbienintangservtasa16ivatot,
        Totales.IvaAcreditableTot.asoactiapliproppagaimporbienintangservtasa16ivatot,
        Totales.IvaAcreditableTot.ivaacrepagaimporbienintangservtasa16tot,
        Totales.IvaAcreditableTot.excluactigravivaincluimportot,
        Totales.IvaAcreditableTot.asoacticualaplipropivaincluimpor,
        Totales.IvaAcreditableTot.ivaacreincluimpor
    FROM(
        SELECT  *
        FROM    $plata_diot_inftotimpiva$
        WHERE   id_ejecucion = '$IDBATCH$' or numeroOperacion in ($NUMEROSOPERACION$)
        AND admindeclaracion IS NOT NULL $PARTITION_FILTER$
    )
),
ivanoacreditabletot AS(
    SELECT
        rfc,
        contribuyente.bo_id,
        identidecla.numerooperacion,
        identidecla.fechapresentacion,
        id_ejecucion,
        contribuyente.razonsocial,
        declaracion.peridiocidad,
        declaracion.periodo,
        declaracion.tipodeclara,
        declaracion.tipocomp,
        Totales.IvaNoAcreditableTot.asoacticualapliproppagarfntota,
        Totales.IvaNoAcreditableTot.asonocumpreqpagarfn,
        Totales.IvaNoAcreditableTot.asoactiexepagarfn,
        Totales.IvaNoAcreditableTot.asoactinoobjpagarfn,
        Totales.IvaNoAcreditableTot.totactactipagarfn,
        Totales.IvaNoAcreditableTot.asoactcualapliproppagarfstota,
        Totales.IvaNoAcreditableTot.asonocumpreqpagarfs,
        Totales.IvaNoAcreditableTot.asoactiexepagarfs,
        Totales.IvaNoAcreditableTot.asoactinoobjpagarfs,
        Totales.IvaNoAcreditableTot.totactactipagarfs,
        Totales.IvaNoAcreditableTot.asoacticualapliproppagarftota,
        Totales.IvaNoAcreditableTot.asonocumpreqpagarf,
        Totales.IvaNoAcreditableTot.asoactiexepagarf,
        Totales.IvaNoAcreditableTot.asoactinoobjpagarf,
        Totales.IvaNoAcreditableTot.totactactipagarf,
        Totales.IvaNoAcreditableTot.asoacticualapliproptotpagatasa16iva,
        Totales.IvaNoAcreditableTot.asonocumpreqtotpagatasa16iva,
        Totales.IvaNoAcreditableTot.asoactiexetotpagatasa16iva,
        Totales.IvaNoAcreditableTot.asoactinoobjtotpagatasa16iva,
        Totales.IvaNoAcreditableTot.totpagatasa16iva,
        Totales.IvaNoAcreditableTot.asoactiaplipropivasininclimportota,
        Totales.IvaNoAcreditableTot.asonocumpreqivasinincimportot,
        Totales.IvaNoAcreditableTot.asoactiexeivasininclimportot,
        Totales.IvaNoAcreditableTot.asoactinoobjivasininclimportot,
        Totales.IvaNoAcreditableTot.totivasininclimportot,
        Totales.IvaNoAcreditableTot.asoactcualapliproppagaimporaduabientangtasa16ivatota,
        Totales.IvaNoAcreditableTot.asonocumpreqpagaimporaduabientangtasa16iva,
        Totales.IvaNoAcreditableTot.asoactiexepagaimporaduabientangtasa16iva,
        Totales.IvaNoAcreditableTot.asoactinoobjpagaimporaduabientangtasa16iva,
        Totales.IvaNoAcreditableTot.totactactipagaimporaduabientangtasa16ivatot,
        Totales.IvaNoAcreditableTot.asoactiapliproppagaimporbienintangservtasa16ivatota,
        Totales.IvaNoAcreditableTot.asonocumpreqpagaimporbienintangservtasa16iva,
        Totales.IvaNoAcreditableTot.asoactexepagaimporbienintangservtasa16iva,
        Totales.IvaNoAcreditableTot.asoactinoobjpagaimporbienintangservtasa16iva,
        Totales.IvaNoAcreditableTot.totactactipagaimporbienintangservtasa16iva,
        Totales.IvaNoAcreditableTot.asoacticualaplipropsumaivaincluimpor,
        Totales.IvaNoAcreditableTot.asonocumpreqsumaivaincluimpor,
        Totales.IvaNoAcreditableTot.asoactiexesumaivaincluimpor,
        Totales.IvaNoAcreditableTot.asoactinoobjsumaivaincluimpor,
        Totales.IvaNoAcreditableTot.totsumaivainluimporta
    FROM(
        SELECT  *
        FROM    $plata_diot_inftotimpiva$
        WHERE   id_ejecucion = '$IDBATCH$' or numeroOperacion in ($NUMEROSOPERACION$)
        AND admindeclaracion IS NOT NULL $PARTITION_FILTER$
    )
),
datosadicionalestot AS(
    SELECT
        rfc,
        contribuyente.bo_id,
        identidecla.numerooperacion,
        identidecla.fechapresentacion,
        id_ejecucion,
        contribuyente.razonsocial,
        declaracion.peridiocidad,
        declaracion.periodo,
        declaracion.tipodeclara,
        declaracion.tipocomp,
        Totales.DatosAdicionalesTot.totivaretecontribu,
        Totales.DatosAdicionalesTot.totactactipagaimporbienservnopagaivaexe,
        Totales.DatosAdicionalesTot.totactactipaganopagaivaexe,
        Totales.DatosAdicionalesTot.demasactactipagatasa0ivatot,
        Totales.DatosAdicionalesTot.totactactinoobjivarealiterrinac,
        Totales.DatosAdicionalesTot.totactactinoobjivanocontestabterrinac
    FROM(
        SELECT  *
        FROM    $plata_diot_inftotimpiva$
        WHERE   id_ejecucion = '$IDBATCH$' or numeroOperacion in ($NUMEROSOPERACION$)
        AND admindeclaracion IS NOT NULL $PARTITION_FILTER$
    )
)

INSERT INTO $diot_inftotimpiva$
SELECT DISTINCT
     A.rfc AS rfcdeclarante,
     A.bo_id,
     A.numerooperacion,
     A.fechapresentacion,
     A.razonsocial,
     A.peridiocidad,
     A.periodo,
     A.tipodeclara,
     A.tipocomp,
     CAST(A.valtotactactipagatasa16ivatot AS DECIMAL(16,0)) AS valtotactactipagatasa16ivatot,
     CAST(A.ivapagatasa16tot AS DECIMAL(16,0)) AS ivapagatasa16tot,
     CAST(A.montivapaganoacretasa16 AS DECIMAL(16,0)) AS montivapaganoacretasa16,
     CAST(A.valtotactactipagatasa11 AS DECIMAL(16,0)) AS valtotactactipagatasa11,
     CAST(A.ivapagatasa11tot AS DECIMAL(16,0)) AS ivapagatasa11tot,
     CAST(A.montivapaganoacretasa11 AS DECIMAL(16,0)) AS montivapaganoacretasa11,
     CAST(A.valactactipagarfntot AS DECIMAL(16,0)) AS valactactipagarfntot,
     CAST(A.ivapagarfntot AS DECIMAL(16,0)) AS ivapagarfntot,
     CAST(A.montivapaganoacrerfn AS DECIMAL(16,0)) AS montivapaganoacrerfn,
     CAST(A.valactactirfs AS DECIMAL(16,0)) AS valactactirfs,
     CAST(A.ivapagarfstot AS DECIMAL(16,0)) AS ivapagarfstot,
     CAST(A.montivapaganoacrerfs AS DECIMAL(16,0)) AS montivapaganoacrerfs,
     CAST(A.ivapagatrslacontri AS DECIMAL(16,0)) AS ivapagatrslacontri,
     CAST(A.montoivapaganoacretrslacontri AS DECIMAL(16,0)) AS montoivapaganoacretrslacontri,
     CAST(A.valactactipagaimpbienservitasa16ivatot AS DECIMAL(16,0)) AS valactactipagaimpbienservitasa16ivatot,
     CAST(A.ivapagaimpbienservitasa16ivatot AS DECIMAL(16,0)) AS ivapagaimpbienservitasa16ivatot,
     CAST(A.montivapaganoacreimporbienservtasa16 AS DECIMAL(16,0)) AS montivapaganoacreimporbienservtasa16,
     CAST(A.valactactipagaimpobienservinopagaivaexentotot AS DECIMAL(16,0)) AS valactactipagaimpobienservinopagaivaexentotot,
     CAST(A.valactactipaganopagaivaexentotot AS DECIMAL(16,0)) AS valactactipaganopagaivaexentotot,
     CAST(A.demasactactipagatasa0iva AS DECIMAL(16,0)) AS demasactactipagatasa0iva,
     CAST(A.actactinoobjiva AS DECIMAL(16,0)) AS actactinoobjiva,
     CAST(A.ivapagretecontribu AS DECIMAL(16,0)) AS ivapagretecontribu,
     CAST(A.ivapagadevdesbonsobadqmercgastgenertot AS DECIMAL(16,0)) AS ivapagadevdesbonsobadqmercgastgenertot,
     CAST(B.valactactipagarfntota AS DECIMAL(16,0)) AS valactactipagarfntota,
     CAST(B.devdesbonactactipagarfn AS DECIMAL(16,0)) AS devdesbonactactipagarfn,
     CAST(B.valnetactactipagarfntot AS DECIMAL(16,0)) AS valnetactactipagarfntot,
     CAST(B.ivapagaactactipagarfn AS DECIMAL(16,0)) AS ivapagaactactipagarfn,
     CAST(B.valactactipagarfstot AS DECIMAL(16,0)) AS valactactipagarfstot,
     CAST(B.devdesbonactactipagarfs AS DECIMAL(16,0)) AS devdesbonactactipagarfs,
     CAST(B.valnetactactipagarfstot AS DECIMAL(16,0)) AS valnetactactipagarfstot,
     CAST(B.ivapagaactactipagarfs AS DECIMAL(16,0)) AS ivapagaactactipagarfs,
     CAST(B.valactactipagarf AS DECIMAL(16,0)) AS valactactipagarf,
     CAST(B.devdesbonactactipagarf AS DECIMAL(16,0)) AS devdesbonactactipagarf,
     CAST(B.valnetactactipagarftot AS DECIMAL(16,0)) AS valnetactactipagarftot,
     CAST(B.ivapagaactactipagarf AS DECIMAL(16,0)) AS ivapagaactactipagarf,
     CAST(B.valactactitotpagatasa16iva AS DECIMAL(16,0)) AS valactactitotpagatasa16iva,
     CAST(B.devdesbontotpagatasa16iva AS DECIMAL(16,0)) AS devdesbontotpagatasa16iva,
     CAST(B.valnetactactipagatasa16ivatot AS DECIMAL(16,0)) AS valnetactactipagatasa16ivatot,
     CAST(B.ivapagatotpagatasa16tot AS DECIMAL(16,0)) AS ivapagatotpagatasa16tot,
     CAST(B.ivapagasinincluimpor AS DECIMAL(16,0)) AS ivapagasinincluimpor,
     CAST(B.valactactipagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS valactactipagaimporaduabientangtasa16iva,
     CAST(B.devdesbonpagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS devdesbonpagaimporaduabientangtasa16iva,
     CAST(B.valnetactactipagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS valnetactactipagaimporaduabientangtasa16iva,
     CAST(B.ivapagaimporaduabientangtasa16tot AS DECIMAL(16,0)) AS ivapagaimporaduabientangtasa16tot,
     CAST(B.valactactipagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS valactactipagaimporbienintangservtasa16iva,
     CAST(B.devdesbonpagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS devdesbonpagaimporbienintangservtasa16iva,
     CAST(B.valnetactactipagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS valnetactactipagaimporbienintangservtasa16iva,
     CAST(B.ivapagaimporbienintangservtasa16tot AS DECIMAL(16,0)) AS ivapagaimporbienintangservtasa16tot,
     CAST(B.ivapagasumimpvalagreincluimpor AS DECIMAL(16,0)) AS ivapagasumimpvalagreincluimpor,
     CAST(C.excluactigravpagarfn AS DECIMAL(16,0)) AS excluactigravpagarfn,
     CAST(C.asoacticualapliproppagarfntot AS DECIMAL(16,0)) AS asoacticualapliproppagarfntot,
     CAST(C.ivaacrepagarfn AS DECIMAL(16,0)) AS ivaacrepagarfn,
     CAST(C.excluactigravpagarfs AS DECIMAL(16,0)) AS excluactigravpagarfs,
     CAST(C.asoacticualapliproppagarfstot AS DECIMAL(16,0)) AS asoacticualapliproppagarfstot,
     CAST(C.ivaacrepagarfs AS DECIMAL(16,0)) AS ivaacrepagarfs,
     CAST(C.excluactigravpagarf AS DECIMAL(16,0)) AS excluactigravpagarf,
     CAST(C.asoacticualapliproppagarf AS DECIMAL(16,0)) AS asoacticualapliproppagarf,
     CAST(C.ivaacrepagarf AS DECIMAL(16,0)) AS ivaacrepagarf,
     CAST(C.excluactigravtotpagatasa16iva AS DECIMAL(16,0)) AS excluactigravtotpagatasa16iva,
     CAST(C.asoacticualapliproppagatasa16ivatot AS DECIMAL(16,0)) AS asoacticualapliproppagatasa16ivatot,
     CAST(C.ivaacretotpagatasa16 AS DECIMAL(16,0)) AS ivaacretotpagatasa16,
     CAST(C.excluactigravivaincluimpor AS DECIMAL(16,0)) AS excluactigravivaincluimpor,
     CAST(C.asoactiaplipropivasininclimportot AS DECIMAL(16,0)) AS asoactiaplipropivasininclimportot,
     CAST(C.ivaacreivasininclimpor AS DECIMAL(16,0)) AS ivaacreivasininclimpor,
     CAST(C.excluactigravpagaimporaduabientangtasa16ivatot AS DECIMAL(16,0)) AS excluactigravpagaimporaduabientangtasa16ivatot,
     CAST(C.asoacticualapliproppagaimporaduabientangtasa16ivatot AS DECIMAL(16,0)) AS asoacticualapliproppagaimporaduabientangtasa16ivatot,
     CAST(C.ivaacrepagaimpoaduabientangtasa16ivatot AS DECIMAL(16,0)) AS ivaacrepagaimpoaduabientangtasa16ivatot,
     CAST(C.excluactigravpagaimporbienintangservtasa16ivatot AS DECIMAL(16,0)) AS excluactigravpagaimporbienintangservtasa16ivatot,
     CAST(C.asoactiapliproppagaimporbienintangservtasa16ivatot AS DECIMAL(16,0)) AS asoactiapliproppagaimporbienintangservtasa16ivatot,
     CAST(C.ivaacrepagaimporbienintangservtasa16tot AS DECIMAL(16,0)) AS ivaacrepagaimporbienintangservtasa16tot,
     CAST(C.excluactigravivaincluimportot AS DECIMAL(16,0)) AS excluactigravivaincluimportot,
     CAST(C.asoacticualaplipropivaincluimpor AS DECIMAL(16,0)) AS asoacticualaplipropivaincluimpor,
     CAST(C.ivaacreincluimpor AS DECIMAL(16,0)) AS ivaacreincluimpor,
     CAST(D.asoacticualapliproppagarfntota AS DECIMAL(16,0)) AS asoacticualapliproppagarfntota,
     CAST(D.asonocumpreqpagarfn AS DECIMAL(16,0)) AS asonocumpreqpagarfn,
     CAST(D.asoactiexepagarfn AS DECIMAL(16,0)) AS asoactiexepagarfn,
     CAST(D.asoactinoobjpagarfn AS DECIMAL(16,0)) AS asoactinoobjpagarfn,
     CAST(D.totactactipagarfn AS DECIMAL(16,0)) AS totactactipagarfn,
     CAST(D.asoactcualapliproppagarfstota AS DECIMAL(16,0)) AS asoactcualapliproppagarfstota,
     CAST(D.asonocumpreqpagarfs AS DECIMAL(16,0)) AS asonocumpreqpagarfs,
     CAST(D.asoactiexepagarfs AS DECIMAL(16,0)) AS asoactiexepagarfs,
     CAST(D.asoactinoobjpagarfs AS DECIMAL(16,0)) AS asoactinoobjpagarfs,
     CAST(D.totactactipagarfs AS DECIMAL(16,0)) AS totactactipagarfs,
     CAST(D.asoacticualapliproppagarftota AS DECIMAL(16,0)) AS asoacticualapliproppagarftota,
     CAST(D.asonocumpreqpagarf AS DECIMAL(16,0)) AS asonocumpreqpagarf,
     CAST(D.asoactiexepagarf AS DECIMAL(16,0)) AS asoactiexepagarf,
     CAST(D.asoactinoobjpagarf AS DECIMAL(16,0)) AS asoactinoobjpagarf,
     CAST(D.totactactipagarf AS DECIMAL(16,0)) AS totactactipagarf,
     CAST(D.asoacticualapliproptotpagatasa16iva AS DECIMAL(16,0)) AS asoacticualapliproptotpagatasa16iva,
     CAST(D.asonocumpreqtotpagatasa16iva AS DECIMAL(16,0)) AS asonocumpreqtotpagatasa16iva,
     CAST(D.asoactiexetotpagatasa16iva AS DECIMAL(16,0)) AS asoactiexetotpagatasa16iva,
     CAST(D.asoactinoobjtotpagatasa16iva AS DECIMAL(16,0)) AS asoactinoobjtotpagatasa16iva,
     CAST(D.totpagatasa16iva AS DECIMAL(16,0)) AS totpagatasa16iva,
     CAST(D.asoactiaplipropivasininclimportota AS DECIMAL(16,0)) AS asoactiaplipropivasininclimportota,
     CAST(D.asonocumpreqivasinincimportot AS DECIMAL(16,0)) AS asonocumpreqivasinincimportot,
     CAST(D.asoactiexeivasininclimportot AS DECIMAL(16,0)) AS asoactiexeivasininclimportot,
     CAST(D.asoactinoobjivasininclimportot AS DECIMAL(16,0)) AS asoactinoobjivasininclimportot,
     CAST(D.totivasininclimportot AS DECIMAL(16,0)) AS totivasininclimportot,
     CAST(D.asoactcualapliproppagaimporaduabientangtasa16ivatota AS DECIMAL(16,0)) AS asoactcualapliproppagaimporaduabientangtasa16ivatota,
     CAST(D.asonocumpreqpagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS asonocumpreqpagaimporaduabientangtasa16iva,
     CAST(D.asoactiexepagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS asoactiexepagaimporaduabientangtasa16iva,
     CAST(D.asoactinoobjpagaimporaduabientangtasa16iva AS DECIMAL(16,0)) AS asoactinoobjpagaimporaduabientangtasa16iva,
     CAST(D.totactactipagaimporaduabientangtasa16ivatot AS DECIMAL(16,0)) AS totactactipagaimporaduabientangtasa16ivatot,
     CAST(D.asoactiapliproppagaimporbienintangservtasa16ivatota AS DECIMAL(16,0)) AS asoactiapliproppagaimporbienintangservtasa16ivatota,
     CAST(D.asonocumpreqpagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS asonocumpreqpagaimporbienintangservtasa16iva,
     CAST(D.asoactexepagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS asoactexepagaimporbienintangservtasa16iva,
     CAST(D.asoactinoobjpagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS asoactinoobjpagaimporbienintangservtasa16iva,
     CAST(D.totactactipagaimporbienintangservtasa16iva AS DECIMAL(16,0)) AS totactactipagaimporbienintangservtasa16iva,
     CAST(D.asoacticualaplipropsumaivaincluimpor AS DECIMAL(16,0)) AS asoacticualaplipropsumaivaincluimpor,
     CAST(D.asonocumpreqsumaivaincluimpor AS DECIMAL(16,0)) AS asonocumpreqsumaivaincluimpor,
     CAST(D.asoactiexesumaivaincluimpor AS DECIMAL(16,0)) AS asoactiexesumaivaincluimpor,
     CAST(D.asoactinoobjsumaivaincluimpor AS DECIMAL(16,0)) AS asoactinoobjsumaivaincluimpor,
     CAST(D.totsumaivainluimporta AS DECIMAL(16,0)) AS totsumaivainluimporta,
     CAST(E.totivaretecontribu AS DECIMAL(16,0)) AS totivaretecontribu,
     CAST(E.totactactipagaimporbienservnopagaivaexe AS DECIMAL(16,0)) AS totactactipagaimporbienservnopagaivaexe,
     CAST(E.totactactipaganopagaivaexe AS DECIMAL(16,0)) AS totactactipaganopagaivaexe,
     CAST(E.demasactactipagatasa0ivatot AS DECIMAL(16,0)) AS demasactactipagatasa0ivatot,
     CAST(E.totactactinoobjivarealiterrinac AS DECIMAL(16,0)) AS totactactinoobjivarealiterrinac,
     CAST(E.totactactinoobjivanocontestabterrinac AS DECIMAL(16,0)) AS totactactinoobjivanocontestabterrinac,
     A.id_ejecucion,
     A.fechadesdoble AS fechacargadwh,
     FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP, "America/Mexico_City") AS fechadesdoble,
     date_trunc('MM', A.fechaPresentacion) AS p_fechapresentacion,
     'I' AS operacion
 FROM infototreportados A
 FULL OUTER JOIN valactactitotales B ON A.id_ejecucion = B.id_ejecucion AND A.numerooperacion = B.numerooperacion
 FULL OUTER JOIN ivaacreditabletot C ON B.id_ejecucion = C.id_ejecucion AND B.numerooperacion = C.numerooperacion
 FULL OUTER JOIN ivanoacreditabletot D ON C.id_ejecucion = D.id_ejecucion AND C.numerooperacion = D.numerooperacion
 FULL OUTER JOIN datosadicionalestot E ON D.id_ejecucion = E.id_ejecucion AND D.numerooperacion = E.numerooperacion

