package sat.diot.ingesta.entities

object Catalogos {

  val estatusProceso = List(
    (100, "Procesando Land"),
    (101, "Terminado Land Exitosamente"),
    (102, "Error en Land"),
    (200, "Procesando Bronce "),
    (201, "Terminado Bronce Exitosamente"),
    (202, "Error en Bronce"),
    (203, "Sin declaraciones en Bronce"),
    (300, "Procesando Plata"),
    (301, "Terminado Plata Exitosamente"),
    (302, "Error en Plata"),
    (400, "Procesando Oro"),
    (401, "Terminado Oro Exitosamente"),
    (402, "Error en Oro"),
    (500, "Procesando Exportacion NPSI"),
    (501, "Terminado Exportacion NPSI Exitosamente"),
    (502, "Error en Exportacion NPSI"),
    (600, "Procesando Exportacion GZIP"),
    (601, "Terminado Exportacion GZIP Exitosamente"),
    (602, "Error en Exportacion GZIP"),
    (700, "PROCESANDO_CONCILIACION_PLATA"),
    (701, "TERMINADO_CONCILIACION_PLATA_EXITOSAMENTE"),
    (702, "ERROR_CONCILIACION_PLATA"),
    (800, "PROCESANDO_CONCILIACION_ORO"),
    (801, "TERMINADO_CONCILIACION_ORO_EXITOSAMENTE"),
    (802, "ERROR_CONCILIACION_ORO"),
    (900, "PROCESANDO_CIFRAS_DETALLE_BRONCE"),
    (901, "TERMINADO_CIFRAS_DETALLE_BRONCE_EXITOSAMENTE"),
    (902, "ERROR_CIFRAS_DETALLE_BRONCE"),
    (1000, "PROCESANDO_CIFRAS_DETALLE_PLATA"),
    (1001, "TERMINADO_CIFRAS_DETALLE_PLATA_EXITOSAMENTE"),
    (1002, "ERROR_CIFRAS_DETALLE_PLATA"),
    (1100, "PROCESANDO_CIFRAS_DETALLE_ORO"),
    (1101, "TERMINADO_CIFRAS_DETALLE_ORO_EXITOSAMENTE"),
    (1102, "ERROR_CIFRAS_DETALLE_ORO"),
    (1200, "PROCESANDO_ENVIO_GZIPS"),
    (1201, "TERMINADO_ENVIO_GZIPS_EXITOSAMENTE"),
    (1202, "ERROR_ENVIO_GZIPS")
  )
}

object CatalogoProceso {
  val REGISTRADO = 0
  val PROCESANDOLAND = 100
  val TERMINADOLANDEXITOSAMENTE = 101
  val ERRORENLAND = 102
  val PROCESANDOBRONCE = 200
  val TERMINADOBRONCEEXITOSAMENTE = 201
  val ERRORENBRONCE = 202
  val SINDECLARACIONESBRONCE = 203
  val PROCESANDOPLATA = 300
  val TERMINADOPLATAEXITOSAMENTE = 301
  val ERRORENPLATA = 302
  val PROCESANDOORO = 400
  val TERMINADOOROEXITOSAMENTE = 401
  val ERRORENORO = 402
  val PROCESANDOEXPORTACIONNPSI = 500
  val TERMINADOEXPORTACIONNPSIEXITOSAMENTE = 501
  val ERRORENEXPORTACIONNPSI = 502
  val PROCESANDOEXPORTACIONGZIP = 600
  val TERMINADOEXPORTACIONGZIPEXITOSAMENTE = 601
  val ERRORENEXPORTACIONGZIP = 602
  val PROCESANDO_CONCILIACION_PLATA = 700
  val TERMINADO_CONCILIACION_PLATA_EXITOSAMENTE = 701
  val ERROR_CONCILIACION_PLATA = 702
  val PROCESANDO_CONCILIACION_ORO = 800
  val TERMINADO_CONCILIACION_ORO_EXITOSAMENTE = 801
  val ERROR_CONCILIACION_ORO = 802
  val PROCESANDO_CIFRAS_DETALLE_BRONCE = 900
  val TERMINADO_CIFRAS_DETALLE_BRONCE_EXITOSAMENTE = 901
  val ERROR_CIFRAS_DETALLE_BRONCE = 902
  val PROCESANDO_CIFRAS_DETALLE_PLATA = 1000
  val TERMINADO_CIFRAS_DETALLE_PLATA_EXITOSAMENTE = 1001
  val ERROR_CIFRAS_DETALLE_PLATA = 1002
  val PROCESANDO_CIFRAS_DETALLE_ORO = 1100
  val TERMINADO_CIFRAS_DETALLE_ORO_EXITOSAMENTE = 1101
  val ERROR_CIFRAS_DETALLE_ORO = 1102
  val PROCESANDO_ENVIO_GZIPS = 1200
  val TERMINADO_ENVIO_GZIPS_EXITOSAMENTE = 1201
  val ERROR_ENVIO_GZIPS = 1202
}
