CREATE TABLE IF NOT EXISTS $diot_decinfopeter$ (
`rfcdeclarante` 		STRING COMMENT '{"metadata": "Registro Federal del Contribuyente.", "length": 13, "claveSat":"206005", "tipoDato":"STRING", "precisionDecimal": null}',
`bo_id` STRING COMMENT '{"metadata": "Identificador del contribuyente.", "length": 50, "claveSat":"SAT_206012", "tipoDato":"STRING", "precisionDecimal": null}',
`numerooperacion` 		LONG COMMENT '{"metadata": "Número de operación.", "length": null, "claveSat":"SAT_24006", "tipoDato":"BIGINT", "precisionDecimal": null}',
`fechapresentacion` 	TIMESTAMP COMMENT '{"metadata": "Fecha de presentación de la declaración.", "length": null, "claveSat":"SAT_24001", "tipoDato":"TIMESTAMP", "precisionDecimal": null}',
`tipopersona` STRING COMMENT '{"metadata": "Tipo de persona.", "length": 1, "claveSat":"SAT_9", "tipoDato":"STRING", "precisionDecimal": null}',
`apellidopaterno` STRING COMMENT '{"metadata": "Apellido paterno.", "length": 300, "claveSat":"270018", "tipoDato":"STRING", "precisionDecimal": null}',
`apellidomaterno` STRING COMMENT '{"metadata": "Apellido materno.", "length": 300, "claveSat":"270019", "tipoDato":"STRING", "precisionDecimal": null}',
`nombre` STRING COMMENT '{"metadata": "Nombre (s).", "length": 300, "claveSat":"270017", "tipoDato":"STRING", "precisionDecimal": null}',
`razonsocial` STRING COMMENT '{"metadata": "Denominación o razón social.", "length": 300, "claveSat":"206011", "tipoDato":"STRING", "precisionDecimal": null}',
`razonsocialhistorica` STRING COMMENT '{"metadata": "Denominación o razón social histórica.", "length": 300, "claveSat":"SAT_206001", "tipoDato":"STRING", "precisionDecimal": null}',
`idtiposoc` STRING COMMENT '{"metadata": "Cve tipo sociedad","length": null, "claveSat":"SAT_206002","tipoDato":"STRING","precisionDecimal":null}',
`desctiposoc` STRING COMMENT '{"metadata": "Descripción tipo de sociedad","length": null, "claveSat":"SAT_206003","tipoDato":"STRING","precisionDecimal":null}',
`iddesconcentrada` STRING COMMENT '{"metadata": "Desconcentrada.", "length": 5, "claveSat":"SAT_206004", "tipoDato":"STRING", "precisionDecimal": null}',
`desdesconcentrada` STRING COMMENT '{"metadata": "Descripción desconcentrada.", "length": 255, "claveSat":"SAT_0101005", "tipoDato":"STRING", "precisionDecimal": null}',
`verformu` 			STRING COMMENT '{"metadata": "Versión del formulario.", "length": 2, "claveSat":"SAT_206006", "tipoDato":"STRING", "precisionDecimal": null}',
`fechaingresoapp` TIMESTAMP COMMENT '{"metadata": "Fecha de ingreso a la aplicación.", "length": null, "claveSat":"SAT_206007", "tipoDato":"TIMESTAMP", "precisionDecimal": null}',
`ejercicio` 			SMALLINT COMMENT '{"metadata": "Ejericio de la declaración.", "length": null, "claveSat":"206010", "tipoDato":"SMALLINT", "precisionDecimal": null}',
`peridiocidad` STRING COMMENT '{"metadata": "Peridiocidad","length": null, "claveSat":"206848","tipoDato":"STRING","precisionDecimal":null}',
`periodo` STRING COMMENT '{"metadata": "Periodo","length": null, "claveSat":"206280","tipoDato":"STRING","precisionDecimal":null}',
`tipodeclara` STRING COMMENT '{"metadata": "Tipo de declaración","length": null, "claveSat":"205002","tipoDato":"STRING","precisionDecimal":null}',
`tipocomp` STRING COMMENT '{"metadata": "Tipo de complementaria","length": null, "claveSat":"207001","tipoDato":"STRING","precisionDecimal":null}',
`obligaciones` SMALLINT COMMENT '{"metadata": "Obligaciones.", "length": null, "claveSat":"SAT_206008", "tipoDato":"SMALLINT", "precisionDecimal": null}',
`vencimientoobligacion` TIMESTAMP COMMENT '{"metadata": "Vencimiento de la obligación","length": null, "claveSat":"SAT_206009","tipoDato":" TIMESTAMP","precisionDecimal":null}',
`mediopresentacion` SMALLINT COMMENT '{"metadata": "Medio de presentación","length": null, "claveSat":"SAT_206010","tipoDato":"DECIMAL(38,18)","precisionDecimal":null}',
`alsc` STRING COMMENT '{"metadata": "ALSC donde presentó la declaración","length": null, "claveSat":"SAT_206011","tipoDato":"STRING","precisionDecimal":null}',
`totaloperacionesrelaciona` DECIMAL(30,0) COMMENT '{"metadata": "Total de operaciones que relaciona","length": null, "claveSat":"206303","tipoDato":"DECIMAL(38,18)","precisionDecimal":null}',
`determinivaacreasocact` STRING COMMENT '{"metadata": "¿Determinaste IVA acreditable asociado a actividades mixtas?","length": null, "claveSat":"207081","tipoDato":"STRING","precisionDecimal":null}',
`montotactacticausimpperiodecla` DECIMAL(16,0) COMMENT '{"metadata": "Monto total de los actos o actividades que causaron el impuesto en el periodo que se declara (actos gravados)","length": null, "claveSat":"207081-1","tipoDato":"DECIMAL(38,18)","precisionDecimal":null}',
`montotactactireaperdecla` DECIMAL(16,0) COMMENT '{"metadata": "Monto total de los actos o actividades realizados en el periodo que se declara (total de actos incluidos exentos y no objeto)","length": null, "claveSat":"207081-2","tipoDato":"DECIMAL(38,18)","precisionDecimal":null}',
`montotactacticauimpaniocalinmant` DECIMAL(16,0) COMMENT '{"metadata": "Monto total de los actos o actividades que causaron el impuesto en el año de calendario inmediato anterior (actos gravados)","length": null, "claveSat":"207081-3","tipoDato":"DECIMAL(38,18)","precisionDecimal":null}',
`montotactactireaniocalinmant` DECIMAL(16,0) COMMENT '{"metadata": "Monto total de los actos o actividades realizados en el año de calendario inmediato anterior (total de actos incluidos exentos y no objeto)","length": null, "claveSat":"207081-4","tipoDato":"DECIMAL(38,18)","precisionDecimal":null}',
`proporcionacreditamiento` STRING COMMENT '{"metadata": "Proporción de acreditamiento","length": null, "claveSat":"207080","tipoDato":"STRING","precisionDecimal":null}',
`aplicasteestimulosfiscales` STRING COMMENT '{"metadata": "¿Aplicaste estímulos fiscales?","length": null, "claveSat":"207207","tipoDato":"STRING","precisionDecimal":null}',
`id_ejecucion` STRING COMMENT '{"metadata": "Identificador Único De Lote De Procesamiento", "length": null, "claveSat":"", "tipoDato":"STRING", "precisionDecimal": null}',
`fechacargadwh` TIMESTAMP  COMMENT '{"metadata": "Fecha de Carga al Data Warehouse", "length": null, "claveSat":"", "tipoDato":"TIMESTAMP ", "precisionDecimal": null}',
`fechadesdoble` TIMESTAMP  COMMENT '{"metadata": "Fecha De Desdoble Azure", "length": null, "claveSat":"", "tipoDato":"TIMESTAMP ", "precisionDecimal": null}',
`p_fechapresentacion` DATE NOT NULL COMMENT '{"metadata": "Particion en formato Timestamp de la fecha de presentacion con formato YYYY-MM-DDTHH:mm:ss", "length": null, "claveSat":null, "tipoDato":"DATE", "precisionDecimal": null}',
`operacion` STRING COMMENT '{"metadata": "Atributo Que Indica Si Es Flujo Normal O Reproceso", "length": null, "claveSat":"", "tipoDato":"STRING", "precisionDecimal": null}',
`periodicidadDesc` STRING COMMENT '{"metadata": "Descripción de la periodicidad","length": 50, "claveSat":"SAT_25","tipoDato":"STRING","precisionDecimal":null}',
`periododesc` STRING COMMENT '{"metadata": "Descripción del periodo","length": 50, "claveSat":"SAT_26","tipoDato":"STRING","precisionDecimal":null}',
`tipoDeclaDesc` STRING COMMENT '{"metadata": "Descripción del tipo de declaración","length": 50, "claveSat":"SAT_24","tipoDato":"STRING","precisionDecimal":null}',
`tipoComplementIdDesc` STRING COMMENT '{"metadata": "Descripción del tipo de complementaria","length": 50, "claveSat":"SAT_33","tipoDato":"STRING","precisionDecimal":null}'
)
USING DELTA
PARTITIONED BY (p_fechapresentacion);