name: Scala Read Delta Table

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install Spark
      uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.4.1'
        hadoop-version: '3'

    - name: Set up sbt
      uses: sbt/setup-sbt@v1

    - name: Run read delta table
      run: sbt "testOnly sat.diot.general.ReadDeltaTableTest"
      
     # run: sbt "testOnly sat.diot.general.GeneralTest Genera DF"
    # - name: Run ScalaTest
    #  run: sbt "testOnly sat.diot.general.GeneralTest Execute SQL query"

    # - name: Run ScalaTest Logger
    #  run: sbt "testOnly sat.diot.Logger.TestLogger Logg Error"
      
