name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Spark
      run: |
        SPARK_VERSION="3.4.1"
        wget https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz
        tar -xzf spark-${SPARK_VERSION}-bin-hadoop3.tgz
        mv spark-${SPARK_VERSION}-bin-hadoop3 /opt/spark
        echo "SPARK_HOME=/opt/spark" >> $GITHUB_ENV
        echo "/opt/spark/bin" >> $GITHUB_PATH

    - name: Set up sbt
      uses: sbt/setup-sbt@v1

    - name: Install docker
      uses: docker/setup-docker-action@v4
      
    - name: Run Docker
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Run Flujo Base DIOT
      run: sbt "testOnly sat.diot.flujobase.Flujobasetest *Flujo Base"
    # - name: Run ScalaTest
    #  run: sbt "testOnly sat.diot.general.GeneralTest Execute SQL query"

    # - name: Run ScalaTest Logger
    #  run: sbt "testOnly sat.diot.Logger.TestLogger Logg Error"
      
